version: "3"

services:
  solana:
    container_name: solana
    image: neonlabsorg/evm_loader:${NEON_EVM_COMMIT}
    environment:
      SOLANA_URL: http://solana:8899
      RUST_LOG: solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
    hostname: solana
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8001"
      - "8001-8009/udp"
    networks:
      - net
    ports:
      - 8899:8899
      - 8900:8900
    healthcheck:
      # Must be available from outside (calling without -u causes premature result)
      test: [ CMD-SHELL, "./wait-for-neon.sh" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    entrypoint: /opt/solana/bin/solana-run-neon.sh

  neon_test_invoke_program_loader:
    container_name: neon_test_invoke_program_loader
    image: neonlabsorg/neon_test_invoke_program:develop
    environment:
      SOLANA_URL: http://solana:8899
    networks:
      - net
    depends_on:
      solana:
        condition: service_healthy
    entrypoint: /opt/neon-test-invoke-program.sh

  postgres:
    container_name: postgres
    image: postgres:14.0
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: neon-db
      POSTGRES_USER: neon-proxy
      POSTGRES_PASSWORD: neon-proxy-pass
    hostname: postgres
    healthcheck:
      test: [ CMD-SHELL, "pg_isready -h postgres -p 5432" ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    expose:
      - "5432"
    ports:
      - "5432"
    networks:
      - net

  dbcreation:
    container_name: dbcreation
    image: neonlabsorg/proxy:${REVISION}
    environment:
      SOLANA_URL: http://solana:8899
      POSTGRES_DB: neon-db
      POSTGRES_USER: neon-proxy
      POSTGRES_PASSWORD: neon-proxy-pass
      POSTGRES_HOST: postgres
    entrypoint: /bin/sh
    command: proxy/run-dbcreation.sh
    networks:
      - net
    depends_on:
      postgres:
        condition: service_healthy

  proxy:
    container_name: proxy
    image: neonlabsorg/proxy:${REVISION}
    environment:
      SOLANA_URL: http://solana:8899
      FAUCET_URL: http://faucet:3333
      PROXY_URL: http://proxy:9090/solana
      POSTGRES_DB: neon-db
      POSTGRES_USER: neon-proxy
      POSTGRES_PASSWORD: neon-proxy-pass
      POSTGRES_HOST: postgres
      NEON_CLI_DEBUG_LOG: "YES"
      FUZZ_FAIL_PCT: 0
      GATHER_STATISTICS: "YES"
      CONFIG: ci
      # Comment next two lines, if you want local stand without real gas-price
      PP_SOLANA_URL: ${CI_PP_SOLANA_URL:-https://api.devnet.solana.com}
      PYTH_MAPPING_ACCOUNT: ${CI_PYTH_MAPPING_ACCOUNT:-BmA9Z6FjioHJPpjT39QazZyhDRUdZy2ezwx4GiDdE2u2}
      #
      MIN_OPERATOR_BALANCE_TO_WARN: 4565760000 # = 913152000 * 5 (5 storage accounts) = 4.56576 SOL
      MIN_OPERATOR_BALANCE_TO_ERR: 913152000 # = solana rent 131072 (= Rent-exempt minimum: 0.913152 SOL) SOLs to create a storage
      # Set to 0 + Comment PYTH configuration above, if you want 0 gas-price
      MINIMAL_GAS_PRICE: 1
      #
      ENABLE_PRIVATE_API: "NO"
      ALLOW_UNDERPRICED_TX_WITHOUT_CHAINID: "YES"
      LOG_FULL_OBJECT_INFO: "NO"
      EVM_LOADER: 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
      RUST_BACKTRACE: ${RUST_BACKTRACE:-0}
      COMMIT_LEVEL: "Confirmed"
      # An example of HashiCorp configuration, operator key in base64 lies in the secret_key field
      #   vault kv put -mount=secret neon-proxy/operator-key-2 secret_key=bdSWJ+WwVWdk2XMoxX25monC....A7g+IyA==
#      HVAC_URL: http://vault:8200
#      HVAC_TOKEN: local-test-hvac-token
#      HVAC_MOUNT: secret
#      HVAC_PATH: neon-proxy/
      #
    hostname: proxy
    depends_on:
      solana:
        condition: service_healthy
      dbcreation:
        condition: service_completed_successfully
    ports:
      - 9090:9090
      - 8881:8888
    expose:
      - "8888"
      - "9090"
    networks:
      - net
    entrypoint: proxy/run-test-proxy.sh
    healthcheck:
      test: [ CMD-SHELL, "/opt/health_check_proxy.sh" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  faucet:
    container_name: faucet
    image: neonlabsorg/faucet:${FAUCET_COMMIT}
    environment:
      FAUCET_RPC_BIND: 0.0.0.0
      FAUCET_RPC_PORT: 3333
      FAUCET_WEB3_ENABLE: 'true'
      WEB3_RPC_URL: http://solana:8899
      WEB3_PRIVATE_KEY: 0x4deacb079b4714c38f39508aa8900039f2721ed8686835d43347ba9267da767b
      NEON_ERC20_TOKENS: '["0xB521b9F3484deF53545F276F1DAA50ef0Ca82E2d", "0x8a2a66CA0E5D491A001957edD45A6350bC76D708", "0x914782059DC42d4E590aeFCfdbF004B2EcBB9fAA", "0x7A7510b9b18241C788a7aAE8299D1fA6010D8128"]'
      NEON_ERC20_MAX_AMOUNT: 1000
      FAUCET_SOLANA_ENABLE: 'true'
      SOLANA_URL: http://solana:8899
      NEON_OPERATOR_KEYFILE: /root/.config/solana/id.json
      NEON_ETH_MAX_AMOUNT: 50000
      TEST_FAUCET_INIT_NEON_BALANCE: 100000000
      EVM_LOADER: 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
      NEON_TOKEN_MINT: HPsV9Deocecw3GeZv1FkAPNCBRfuVyfw9MMwjwRe1xaU
      NEON_TOKEN_MINT_DECIMALS: 9
      SOLANA_COMMITMENT: confirmed
      RUST_BACKTRACE: ${RUST_BACKTRACE:-0}
    hostname: faucet
    ports:
      - 3333:3333
    expose:
      - "3333"
    networks:
      - net
    entrypoint: ./run-test-faucet.sh
    depends_on:
      solana:
        condition: service_healthy

  gas_tank:
    container_name: gas_tank
    image: neonlabsorg/proxy:${REVISION}
    environment:
      POSTGRES_DB: neon-db
      POSTGRES_USER: neon-proxy
      POSTGRES_PASSWORD: neon-proxy-pass
      POSTGRES_HOST: postgres
      POSTGRES_TIMEOUT: 15
      SOLANA_URL: http://solana:8899
      INDEXER_ERC20_WRAPPER_WHITELIST: ANY
      START_SLOT: LATEST
    hostname: gas_tank
    entrypoint: ./run-gas-tank.sh
    networks:
      - net
    depends_on:
      solana:
        condition: service_healthy
      dbcreation:
        condition: service_completed_successfully
      faucet:
        condition: service_started

  indexer:
    container_name: indexer
    image: neonlabsorg/proxy:${REVISION}
    environment:
      SOLANA_URL: http://solana:8899
      POSTGRES_DB: neon-db
      POSTGRES_USER: neon-proxy
      POSTGRES_PASSWORD: neon-proxy-pass
      POSTGRES_HOST: postgres
      POSTGRES_TIMEOUT: 15
      GATHER_STATISTICS: "YES"
      LOG_FULL_OBJECT_INFO: "NO"
      CONFIG: ci
      EVM_LOADER: 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
      START_SLOT: continue
    hostname: indexer
    depends_on:
      solana:
        condition: service_healthy
      dbcreation:
        condition: service_completed_successfully
    expose:
      - "8887"
    ports:
      - 8882:8888
    networks:
      - net
    entrypoint: proxy/run-indexer.sh

#  hashicorp:
#    container_name: vault
#    image: hashicorp/vault:latest
#    hostname: vault
#    expose:
#      - 8200
#    ports:
#      - 8200:8200
#    networks:
#      - net
#    entrypoint: vault server -dev -dev-listen-address=0.0.0.0:8200 -dev-root-token-id=local-test-hvac-token

networks:
  net:
